### ISSUE TITLE
Doesn't work with projects using /src/ directory

### ISSUE THREAD

**Issue by ashtonlance** [oslabs-beta/Vantage#88]
My project has all pages/components/ etc etc under the `/src` directory. This breaks the whole lighthouse package since it expects `/pages` to be in the root.

**Comment by ashtonlance** [comment]
I've tried opening a PR but I can't push my branch up due to permission issues.

**Comment by mnoah1** [comment]
Hi @ashtonlance - did you make the change in your own fork?  If so, then from within the fork are you able to select your fork as the head and this repo as the base repository?  Or can you provide any other details on the permissions error?

**Comment by ashtonlance** [comment]
@mnoah1 PR is opened! #91
